// Generated by scripts/generate-image-index.mjs - do not edit by hand.
import image0 from './dornoch-A.png'
import image1 from './dornoch-B.png'
import image2 from './dornoch-C.png'
import image3 from './dornoch-D.png'
import image4 from './dornoch-back.png'
import image5 from './manor-A.png'
import image6 from './manor-B.png'
import image7 from './manor-C.png'
import image8 from './manor-D.png'
import image9 from './manor-back.png'

// Image URL by file name (without .png)
export const Images: Record<string, string> = {
    'dornoch-A': image0,
    'dornoch-B': image1,
    'dornoch-C': image2,
    'dornoch-D': image3,
    'dornoch-back': image4,
    'manor-A': image5,
    'manor-B': image6,
    'manor-C': image7,
    'manor-D': image8,
    'manor-back': image9,
}
