// Generated by scripts/generate-image-index.mjs - do not edit by hand.
import image0 from './back-decade1.png'
import image1 from './back-decade2.png'
import image2 from './back-decade3.png'
import image3 from './back-decade4.png'
import image4 from './d01.png'
import image5 from './d02.png'
import image6 from './d03.png'
import image7 from './d04.png'
import image8 from './d05.png'
import image9 from './d06.png'
import image10 from './d07.png'
import image11 from './d08.png'
import image12 from './d09.png'
import image13 from './d10.png'
import image14 from './d11.png'
import image15 from './d12.png'
import image16 from './d13.png'
import image17 from './d14.png'
import image18 from './d15.png'
import image19 from './d16.png'
import image20 from './d17.png'
import image21 from './d18.png'
import image22 from './d19.png'
import image23 from './d20.png'
import image24 from './d21.png'
import image25 from './d22.png'
import image26 from './d23.png'
import image27 from './d24.png'
import image28 from './d25.png'
import image29 from './d26.png'
import image30 from './d27.png'
import image31 from './d28.png'
import image32 from './d29.png'
import image33 from './d30.png'
import image34 from './era1.png'
import image35 from './era2.png'
import image36 from './gameOver.png'

// Image URL by file name (without .png)
export const Images: Record<string, string> = {
    'back-decade1': image0,
    'back-decade2': image1,
    'back-decade3': image2,
    'back-decade4': image3,
    'd01': image4,
    'd02': image5,
    'd03': image6,
    'd04': image7,
    'd05': image8,
    'd06': image9,
    'd07': image10,
    'd08': image11,
    'd09': image12,
    'd10': image13,
    'd11': image14,
    'd12': image15,
    'd13': image16,
    'd14': image17,
    'd15': image18,
    'd16': image19,
    'd17': image20,
    'd18': image21,
    'd19': image22,
    'd20': image23,
    'd21': image24,
    'd22': image25,
    'd23': image26,
    'd24': image27,
    'd25': image28,
    'd26': image29,
    'd27': image30,
    'd28': image31,
    'd29': image32,
    'd30': image33,
    'era1': image34,
    'era2': image35,
    'gameOver': image36,
}
