export enum ActionType {
    MovePawn = 'MovePawn',
    Tax = 'Tax',
    Invest = 'Invest',
    ChooseShare = 'ChooseShare',
    PointBuy = 'PointBuy',
    ClaimMine = 'ClaimMine',
    LayTrack = 'LayTrack',
    ExtractAndSell = 'ExtractAndSell',
    Hunt = 'Hunt',
    Acquire = 'Acquire',
    GemAction = 'GemAction',
    AgreementPointBuy = 'AgreementPointBuy',
    DiscardAgreement = 'DiscardAgreement',
    LayFreeTrack = 'LayFreeTrack',
    SellVictoryPoints = 'SellVictoryPoints',
    ResolveHunt = 'ResolveHunt',
    SkipBonusInvest = 'SkipBonusInvest',
    EndTurn = 'EndTurn'
}
