packages:
  - "libs/*"
  - "games/*"
  - "apps/*"
  - "config/*"
  - "tools/*"
onlyBuiltDependencies:
  - "camera-controls"
  - "@fortawesome/fontawesome-common-types"
  - "@fortawesome/fontawesome-svg-core"
  - "@fortawesome/free-regular-svg-icons"
  - "@fortawesome/free-solid-svg-icons"
  - "bcrypt"
  - "core-js-pure"
  - "esbuild"
  - "protobufjs"
  - "sharp"
