// Generated by scripts/generate-image-index.mjs - do not edit by hand.
import image0 from './demon.png'
import image1 from './forestTroll.png'
import image2 from './ghost.png'
import image3 from './giantSpider.png'
import image4 from './goblins.png'
import image5 from './hellhound.png'
import image6 from './imps.png'
import image7 from './manticore.png'
import image8 from './mountainTroll.png'
import image9 from './ogre.png'
import image10 from './rats.png'
import image11 from './serpent1.png'
import image12 from './serpent2.png'
import image13 from './succubus.png'
import image14 from './werewolf.png'

// Image URL by file name (without .png)
export const Images: Record<string, string> = {
    'demon': image0,
    'forestTroll': image1,
    'ghost': image2,
    'giantSpider': image3,
    'goblins': image4,
    'hellhound': image5,
    'imps': image6,
    'manticore': image7,
    'mountainTroll': image8,
    'ogre': image9,
    'rats': image10,
    'serpent1': image11,
    'serpent2': image12,
    'succubus': image13,
    'werewolf': image14,
}
