// Generated by scripts/generate-image-index.mjs - do not edit by hand.
import image0 from './dp1-back.png'
import image1 from './dp1.png'
import image2 from './dp2-back.png'
import image3 from './dp2.png'
import image4 from './dp3-back.png'
import image5 from './dp3.png'
import image6 from './dp4.png'
import image7 from './dp5.png'
import image8 from './gcr1-back.png'
import image9 from './gcr1.png'
import image10 from './gcr2-back.png'
import image11 from './gcr2.png'
import image12 from './gcr3-back.png'
import image13 from './gcr3.png'
import image14 from './gcr4.png'
import image15 from './gcr5.png'
import image16 from './wc1-back.png'
import image17 from './wc1.png'
import image18 from './wc2-back.png'
import image19 from './wc2.png'
import image20 from './wc3-back.png'
import image21 from './wc3.png'
import image22 from './wc4.png'
import image23 from './wc5.png'
import image24 from './wwr1-back.png'
import image25 from './wwr1.png'
import image26 from './wwr2-back.png'
import image27 from './wwr2.png'
import image28 from './wwr3-back.png'
import image29 from './wwr3.png'
import image30 from './wwr4.png'
import image31 from './wwr5.png'

// Image URL by file name (without .png)
export const Images: Record<string, string> = {
    'dp1-back': image0,
    'dp1': image1,
    'dp2-back': image2,
    'dp2': image3,
    'dp3-back': image4,
    'dp3': image5,
    'dp4': image6,
    'dp5': image7,
    'gcr1-back': image8,
    'gcr1': image9,
    'gcr2-back': image10,
    'gcr2': image11,
    'gcr3-back': image12,
    'gcr3': image13,
    'gcr4': image14,
    'gcr5': image15,
    'wc1-back': image16,
    'wc1': image17,
    'wc2-back': image18,
    'wc2': image19,
    'wc3-back': image20,
    'wc3': image21,
    'wc4': image22,
    'wc5': image23,
    'wwr1-back': image24,
    'wwr1': image25,
    'wwr2-back': image26,
    'wwr2': image27,
    'wwr3-back': image28,
    'wwr3': image29,
    'wwr4': image30,
    'wwr5': image31,
}
