// Generated by scripts/generate-image-index.mjs - do not edit by hand.
import image0 from './gold2.png'
import image1 from './gold3.png'
import image2 from './gold3s.png'
import image3 from './gold4.png'
import image4 from './gold4s.png'
import image5 from './gold5.png'
import image6 from './gold5s.png'
import image7 from './goldBackA.png'
import image8 from './goldBackB.png'
import image9 from './silver2.png'
import image10 from './silver2s.png'
import image11 from './silver3.png'
import image12 from './silver3s.png'
import image13 from './silver4.png'
import image14 from './silver5.png'
import image15 from './silverBackA.png'
import image16 from './silverBackB.png'

// Image URL by file name (without .png)
export const Images: Record<string, string> = {
    'gold2': image0,
    'gold3': image1,
    'gold3s': image2,
    'gold4': image3,
    'gold4s': image4,
    'gold5': image5,
    'gold5s': image6,
    'goldBackA': image7,
    'goldBackB': image8,
    'silver2': image9,
    'silver2s': image10,
    'silver3': image11,
    'silver3s': image12,
    'silver4': image13,
    'silver5': image14,
    'silverBackA': image15,
    'silverBackB': image16,
}
