// Generated by scripts/generate-image-index.mjs - do not edit by hand.
import image0 from './green-p1.png'
import image1 from './green-p2.png'
import image2 from './green-p3.png'
import image3 from './green-p4.png'
import image4 from './green-p5.png'
import image5 from './purple-p1.png'
import image6 from './purple-p2.png'
import image7 from './purple-p3.png'
import image8 from './purple-p4.png'
import image9 from './purple-p5.png'
import image10 from './red-p1.png'
import image11 from './red-p2.png'
import image12 from './red-p3.png'
import image13 from './red-p4.png'
import image14 from './red-p5.png'
import image15 from './white-p1.png'
import image16 from './white-p2.png'
import image17 from './white-p3.png'
import image18 from './white-p4.png'
import image19 from './white-p5.png'
import image20 from './yellow-p1.png'
import image21 from './yellow-p2.png'
import image22 from './yellow-p3.png'
import image23 from './yellow-p4.png'
import image24 from './yellow-p5.png'

// Image URL by file name (without .png)
export const Images: Record<string, string> = {
    'green-p1': image0,
    'green-p2': image1,
    'green-p3': image2,
    'green-p4': image3,
    'green-p5': image4,
    'purple-p1': image5,
    'purple-p2': image6,
    'purple-p3': image7,
    'purple-p4': image8,
    'purple-p5': image9,
    'red-p1': image10,
    'red-p2': image11,
    'red-p3': image12,
    'red-p4': image13,
    'red-p5': image14,
    'white-p1': image15,
    'white-p2': image16,
    'white-p3': image17,
    'white-p4': image18,
    'white-p5': image19,
    'yellow-p1': image20,
    'yellow-p2': image21,
    'yellow-p3': image22,
    'yellow-p4': image23,
    'yellow-p5': image24,
}
