// Generated by scripts/generate-image-index.mjs - do not edit by hand.
import image0 from './bonusGem.png'
import image1 from './bonusGold.png'
import image2 from './bonusInvest.png'
import image3 from './bonusWeaponLevel.png'
import image4 from './dragon.png'
import image5 from './hit.png'
import image6 from './miss.png'
import image7 from './tracker.png'

// Image URL by file name (without .png)
export const Images: Record<string, string> = {
    'bonusGem': image0,
    'bonusGold': image1,
    'bonusInvest': image2,
    'bonusWeaponLevel': image3,
    'dragon': image4,
    'hit': image5,
    'miss': image6,
    'tracker': image7,
}
